version: '3.3'

services:

  nginx:
    container_name: 'nginx-1.13'
    image: 'nginx:1.13'
    restart: 'always'
    ports:
      - 80:80
    volumes:
      - '../src:/home/admin/lab'
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - 'php'

  php:
    container_name: 'php'
    build: '.docker'
    restart: 'always'
    volumes:
      - '../src:/home/admin/lab'